"""Investment memo PDF export (equity research format)."""

from __future__ import annotations

import io
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _styles():
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title", parent=base["Heading1"], fontSize=18, spaceAfter=12, textColor=colors.HexColor("#0f172a")),
        "heading": ParagraphStyle("Heading", parent=base["Heading2"], fontSize=12, spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#0369a1")),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=10, leading=14, alignment=TA_LEFT),
        "meta": ParagraphStyle("Meta", parent=base["BodyText"], fontSize=9, textColor=colors.grey),
    }


def generate_investment_memo_pdf(report: dict[str, Any], company_name: str) -> bytes:
    """Build an ER-style one-page investment memo PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = _styles()
    story = []

    overview = report.get("company_overview") or {}
    ticker = overview.get("ticker", "N/A")
    story.append(Paragraph(f"Investment Memo — {company_name} ({ticker})", styles["title"]))
    story.append(Paragraph("Equity Research | Generated by Diligence AI", styles["meta"]))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph("Investment Thesis", styles["heading"]))
    story.append(Paragraph(str(report.get("executive_summary", "")), styles["body"]))

    metrics = report.get("financial_analysis") or []
    if metrics:
        story.append(Paragraph("Key Metrics", styles["heading"]))
        rows = [["Metric", "Current", "YoY", "Assessment"]]
        for m in metrics[:6]:
            rows.append([
                str(m.get("metric_name", "")),
                str(m.get("current_value", "")),
                str(m.get("yoy_change", "—")),
                str(m.get("assessment", "")),
            ])
        table = Table(rows, colWidths=[1.5 * inch, 1.2 * inch, 1 * inch, 1.2 * inch])
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e0f2fe")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0c4a6e")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(table)

    risks = report.get("risk_assessment") or []
    if risks:
        story.append(Paragraph("Key Risks", styles["heading"]))
        for risk in risks[:4]:
            story.append(
                Paragraph(
                    f"<b>{risk.get('risk_name', 'Risk')}</b> ({risk.get('severity', 'medium')}): "
                    f"{risk.get('description', '')} <i>[{risk.get('source_section', 'Risk Factors')}]</i>",
                    styles["body"],
                )
            )

    recs = report.get("recommendations") or []
    if recs:
        story.append(Paragraph("Analyst Actions", styles["heading"]))
        for rec in recs[:3]:
            story.append(
                Paragraph(
                    f"• [{rec.get('priority', 'medium').upper()}] {rec.get('action', '')} — {rec.get('rationale', '')}",
                    styles["body"],
                )
            )

    story.append(Spacer(1, 0.3 * inch))
    story.append(
        Paragraph(
            f"Data quality score: {report.get('data_quality_score', 'N/A')}/100. "
            "This memo is for interview/demo purposes and is not investment advice.",
            styles["meta"],
        )
    )

    doc.build(story)
    return buffer.getvalue()
