import { jsPDF } from 'jspdf';

type Report = Record<string, unknown>;

function lines(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

/** Client/server-safe ER memo PDF from analysis report JSON. */
export function buildInvestmentMemoPdf(report: Report, companyName: string): Uint8Array {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' });
  const margin = 54;
  const width = doc.internal.pageSize.getWidth() - margin * 2;
  let y = margin;

  const overview = (report.company_overview as Record<string, string>) || {};
  const ticker = overview.ticker || 'N/A';

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(`Investment Memo — ${companyName} (${ticker})`, margin, y);
  y += 22;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Equity Research | Generated by Diligence AI', margin, y);
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(3, 105, 161);
  doc.text('Investment Thesis', margin, y);
  y += 16;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  for (const line of lines(doc, String(report.executive_summary || ''), width)) {
    if (y > 720) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += 14;
  }
  y += 8;

  const metrics = (report.financial_analysis as Array<Record<string, string>>) || [];
  if (metrics.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(3, 105, 161);
    doc.text('Key Metrics', margin, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    for (const m of metrics.slice(0, 6)) {
      const row = `${m.metric_name}: ${m.current_value} (${m.yoy_change || '—'}) — ${m.assessment || ''}`;
      for (const line of lines(doc, row, width)) {
        if (y > 720) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 12;
      }
    }
    y += 8;
  }

  const risks = (report.risk_assessment as Array<Record<string, string>>) || [];
  if (risks.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(3, 105, 161);
    doc.text('Key Risks', margin, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    for (const risk of risks.slice(0, 4)) {
      const block = `${risk.risk_name} (${risk.severity}): ${risk.description} [${risk.source_section || 'Risk Factors'}]`;
      for (const line of lines(doc, block, width)) {
        if (y > 720) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 12;
      }
      y += 4;
    }
  }

  const recs = (report.recommendations as Array<Record<string, string>>) || [];
  if (recs.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(3, 105, 161);
    doc.text('Analyst Actions', margin, y);
    y += 16;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    for (const rec of recs.slice(0, 3)) {
      const block = `[${(rec.priority || 'medium').toUpperCase()}] ${rec.action} — ${rec.rationale || ''}`;
      for (const line of lines(doc, block, width)) {
        if (y > 720) {
          doc.addPage();
          y = margin;
        }
        doc.text(line, margin, y);
        y += 12;
      }
    }
  }

  y += 12;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Data quality score: ${report.data_quality_score ?? 'N/A'}/100. Demo memo — not investment advice.`,
    margin,
    Math.min(y + 12, 740)
  );

  return doc.output('arraybuffer') as unknown as Uint8Array;
}
